apiVersion: v1
kind: Pod
metadata:
  name: producer
  labels:
    app: producer
spec:
  containers:
    - name: producer
      image: gusanimax/producer:1.6
      ports:
        - containerPort: 5556
          protocol: TCP
  