apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  labels:
    app: producer-svc
spec:
  ports:
    - name: http-producer
      port: 5556
      protocol: TCP
      targetPort: 5556
  type: NodePort
  selector:
    app: producer
  