apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  labels:
    app: producer
spec:
  ports:
    - name: http-producer
      port: 80
      protocol: TCP
      targetPort: 5556
  type: ClusterIP
  selector:
    app: producer
  